version: '2'
services:
  jhipstersampleapplication191011-app:
    image: jhipstersampleapplication191011
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplication191011-mysql:3306/jhipstersampleapplication191011?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstersampleapplication191011-mysql:
    extends:
      file: mysql.yml
      service: jhipstersampleapplication191011-mysql
